// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: payment.proto

package payment_v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
	
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateCheckoutSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlanId        string                 `protobuf:"bytes,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	SuccessUrl    string                 `protobuf:"bytes,2,opt,name=success_url,json=successUrl,proto3" json:"success_url,omitempty"`
	CancelUrl     string                 `protobuf:"bytes,3,opt,name=cancel_url,json=cancelUrl,proto3" json:"cancel_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCheckoutSessionRequest) Reset() {
	*x = CreateCheckoutSessionRequest{}
	mi := &file_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCheckoutSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCheckoutSessionRequest) ProtoMessage() {}

func (x *CreateCheckoutSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCheckoutSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateCheckoutSessionRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCheckoutSessionRequest) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *CreateCheckoutSessionRequest) GetSuccessUrl() string {
	if x != nil {
		return x.SuccessUrl
	}
	return ""
}

func (x *CreateCheckoutSessionRequest) GetCancelUrl() string {
	if x != nil {
		return x.CancelUrl
	}
	return ""
}

type CreateCheckoutSessionResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CheckoutSessionId string                 `protobuf:"bytes,1,opt,name=checkout_session_id,json=checkoutSessionId,proto3" json:"checkout_session_id,omitempty"`
	CheckoutUrl       string                 `protobuf:"bytes,2,opt,name=checkout_url,json=checkoutUrl,proto3" json:"checkout_url,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateCheckoutSessionResponse) Reset() {
	*x = CreateCheckoutSessionResponse{}
	mi := &file_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCheckoutSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCheckoutSessionResponse) ProtoMessage() {}

func (x *CreateCheckoutSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCheckoutSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateCheckoutSessionResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCheckoutSessionResponse) GetCheckoutSessionId() string {
	if x != nil {
		return x.CheckoutSessionId
	}
	return ""
}

func (x *CreateCheckoutSessionResponse) GetCheckoutUrl() string {
	if x != nil {
		return x.CheckoutUrl
	}
	return ""
}

type HandleStripeWebhookRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Payload         string                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	StripeSignature string                 `protobuf:"bytes,2,opt,name=stripe_signature,json=stripeSignature,proto3" json:"stripe_signature,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HandleStripeWebhookRequest) Reset() {
	*x = HandleStripeWebhookRequest{}
	mi := &file_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleStripeWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleStripeWebhookRequest) ProtoMessage() {}

func (x *HandleStripeWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleStripeWebhookRequest.ProtoReflect.Descriptor instead.
func (*HandleStripeWebhookRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{2}
}

func (x *HandleStripeWebhookRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *HandleStripeWebhookRequest) GetStripeSignature() string {
	if x != nil {
		return x.StripeSignature
	}
	return ""
}

type HandleStripeWebhookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleStripeWebhookResponse) Reset() {
	*x = HandleStripeWebhookResponse{}
	mi := &file_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleStripeWebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleStripeWebhookResponse) ProtoMessage() {}

func (x *HandleStripeWebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleStripeWebhookResponse.ProtoReflect.Descriptor instead.
func (*HandleStripeWebhookResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{3}
}

func (x *HandleStripeWebhookResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HandleStripeWebhookResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetSubscriptionInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscriptionInfoRequest) Reset() {
	*x = GetSubscriptionInfoRequest{}
	mi := &file_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionInfoRequest) ProtoMessage() {}

func (x *GetSubscriptionInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionInfoRequest.ProtoReflect.Descriptor instead.
func (*GetSubscriptionInfoRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{4}
}

type GetSubscriptionInfoResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PlanId             string                 `protobuf:"bytes,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	Status             string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	CurrentPeriodStart *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=current_period_start,json=currentPeriodStart,proto3" json:"current_period_start,omitempty"`
	CurrentPeriodEnd   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=current_period_end,json=currentPeriodEnd,proto3" json:"current_period_end,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetSubscriptionInfoResponse) Reset() {
	*x = GetSubscriptionInfoResponse{}
	mi := &file_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionInfoResponse) ProtoMessage() {}

func (x *GetSubscriptionInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionInfoResponse.ProtoReflect.Descriptor instead.
func (*GetSubscriptionInfoResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{5}
}

func (x *GetSubscriptionInfoResponse) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *GetSubscriptionInfoResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetSubscriptionInfoResponse) GetCurrentPeriodStart() *timestamppb.Timestamp {
	if x != nil {
		return x.CurrentPeriodStart
	}
	return nil
}

func (x *GetSubscriptionInfoResponse) GetCurrentPeriodEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.CurrentPeriodEnd
	}
	return nil
}

type GetCurrentSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                  `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentSubscriptionRequest) Reset() {
	*x = GetCurrentSubscriptionRequest{}
	mi := &file_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentSubscriptionRequest) ProtoMessage() {}

func (x *GetCurrentSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{6}
}

func (x *GetCurrentSubscriptionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetCurrentSubscriptionResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Status           string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	PlanId           string                 `protobuf:"bytes,2,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	CurrentPeriodEnd int64                  `protobuf:"varint,3,opt,name=current_period_end,json=currentPeriodEnd,proto3" json:"current_period_end,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetCurrentSubscriptionResponse) Reset() {
	*x = GetCurrentSubscriptionResponse{}
	mi := &file_payment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentSubscriptionResponse) ProtoMessage() {}

func (x *GetCurrentSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*GetCurrentSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{7}
}

func (x *GetCurrentSubscriptionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetCurrentSubscriptionResponse) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *GetCurrentSubscriptionResponse) GetCurrentPeriodEnd() int64 {
	if x != nil {
		return x.CurrentPeriodEnd
	}
	return 0
}

var File_payment_proto protoreflect.FileDescriptor

const file_payment_proto_rawDesc = "" +
	"\n" +
	"\rpayment.proto\x12\n" +
	"payment.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\"w\n" +
	"\x1cCreateCheckoutSessionRequest\x12\x17\n" +
	"\aplan_id\x18\x01 \x01(\tR\x06planId\x12\x1f\n" +
	"\vsuccess_url\x18\x02 \x01(\tR\n" +
	"successUrl\x12\x1d\n" +
	"\n" +
	"cancel_url\x18\x03 \x01(\tR\tcancelUrl\"r\n" +
	"\x1dCreateCheckoutSessionResponse\x12.\n" +
	"\x13checkout_session_id\x18\x01 \x01(\tR\x11checkoutSessionId\x12!\n" +
	"\fcheckout_url\x18\x02 \x01(\tR\vcheckoutUrl\"a\n" +
	"\x1aHandleStripeWebhookRequest\x12\x18\n" +
	"\apayload\x18\x01 \x01(\tR\apayload\x12)\n" +
	"\x10stripe_signature\x18\x02 \x01(\tR\x0fstripeSignature\"Q\n" +
	"\x1bHandleStripeWebhookResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x1c\n" +
	"\x1aGetSubscriptionInfoRequest\"\xe6\x01\n" +
	"\x1bGetSubscriptionInfoResponse\x12\x17\n" +
	"\aplan_id\x18\x01 \x01(\tR\x06planId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12L\n" +
	"\x14current_period_start\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x12currentPeriodStart\x12H\n" +
	"\x12current_period_end\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x10currentPeriodEnd\"8\n" +
	"\x1dGetCurrentSubscriptionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\x7f\n" +
	"\x1eGetCurrentSubscriptionResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x17\n" +
	"\aplan_id\x18\x02 \x01(\tR\x06planId\x12,\n" +
	"\x12current_period_end\x18\x03 \x01(\x03R\x10currentPeriodEnd2\xa5\x04\n" +
	"\x0ePaymentService\x12\x8d\x01\n" +
	"\x15CreateCheckoutSession\x12(.payment.v1.CreateCheckoutSessionRequest\x1a).payment.v1.CreateCheckoutSessionResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/payment/checkout\x12\x86\x01\n" +
	"\x13HandleStripeWebhook\x12&.payment.v1.HandleStripeWebhookRequest\x1a'.payment.v1.HandleStripeWebhookResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/payment/webhook\x12\x88\x01\n" +
	"\x13GetSubscriptionInfo\x12&.payment.v1.GetSubscriptionInfoRequest\x1a'.payment.v1.GetSubscriptionInfoResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/payment/subscription\x12o\n" +
	"\x16GetCurrentSubscription\x12).payment.v1.GetCurrentSubscriptionRequest\x1a*.payment.v1.GetCurrentSubscriptionResponseB1Z/payment_service/pkg/proto/payment/v1;payment_v1b\x06proto3"

var (
	file_payment_proto_rawDescOnce sync.Once
	file_payment_proto_rawDescData []byte
)

func file_payment_proto_rawDescGZIP() []byte {
	file_payment_proto_rawDescOnce.Do(func() {
		file_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)))
	})
	return file_payment_proto_rawDescData
}

var file_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_payment_proto_goTypes = []any{
	(*CreateCheckoutSessionRequest)(nil),   // 0: payment.v1.CreateCheckoutSessionRequest
	(*CreateCheckoutSessionResponse)(nil),  // 1: payment.v1.CreateCheckoutSessionResponse
	(*HandleStripeWebhookRequest)(nil),     // 2: payment.v1.HandleStripeWebhookRequest
	(*HandleStripeWebhookResponse)(nil),    // 3: payment.v1.HandleStripeWebhookResponse
	(*GetSubscriptionInfoRequest)(nil),     // 4: payment.v1.GetSubscriptionInfoRequest
	(*GetSubscriptionInfoResponse)(nil),    // 5: payment.v1.GetSubscriptionInfoResponse
	(*GetCurrentSubscriptionRequest)(nil),  // 6: payment.v1.GetCurrentSubscriptionRequest
	(*GetCurrentSubscriptionResponse)(nil), // 7: payment.v1.GetCurrentSubscriptionResponse
	(*timestamppb.Timestamp)(nil),          // 8: google.protobuf.Timestamp
}
var file_payment_proto_depIdxs = []int32{
	8, // 0: payment.v1.GetSubscriptionInfoResponse.current_period_start:type_name -> google.protobuf.Timestamp
	8, // 1: payment.v1.GetSubscriptionInfoResponse.current_period_end:type_name -> google.protobuf.Timestamp
	0, // 2: payment.v1.PaymentService.CreateCheckoutSession:input_type -> payment.v1.CreateCheckoutSessionRequest
	2, // 3: payment.v1.PaymentService.HandleStripeWebhook:input_type -> payment.v1.HandleStripeWebhookRequest
	4, // 4: payment.v1.PaymentService.GetSubscriptionInfo:input_type -> payment.v1.GetSubscriptionInfoRequest
	6, // 5: payment.v1.PaymentService.GetCurrentSubscription:input_type -> payment.v1.GetCurrentSubscriptionRequest
	1, // 6: payment.v1.PaymentService.CreateCheckoutSession:output_type -> payment.v1.CreateCheckoutSessionResponse
	3, // 7: payment.v1.PaymentService.HandleStripeWebhook:output_type -> payment.v1.HandleStripeWebhookResponse
	5, // 8: payment.v1.PaymentService.GetSubscriptionInfo:output_type -> payment.v1.GetSubscriptionInfoResponse
	7, // 9: payment.v1.PaymentService.GetCurrentSubscription:output_type -> payment.v1.GetCurrentSubscriptionResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_payment_proto_init() }
func file_payment_proto_init() {
	if File_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_proto_goTypes,
		DependencyIndexes: file_payment_proto_depIdxs,
		MessageInfos:      file_payment_proto_msgTypes,
	}.Build()
	File_payment_proto = out.File
	file_payment_proto_goTypes = nil
	file_payment_proto_depIdxs = nil
}
